sudo: false
addons:
  apt:
    packages:
      - build-essential
      - gettext
      - python-dev
      - zlib1g-dev
      - libpq-dev
      - xvfb
      - libtiff4-dev 
      - libjpeg8-dev 
      - libfreetype6-dev 
      - liblcms1-dev 
      - libwebp-dev
      - graphviz-dev 
      - python-setuptools 
      - python3-dev 
      - python-virtualenv 
      - python-pip
      - firefox 
      - automake 
      - libtool 
      - libreadline6 
      - libreadline6-dev 
      - libreadline-dev
      - libsqlite3-dev 
      - libxml2 
      - libxml2-dev 
      - libssl-dev 
      - libbz2-dev 
      - wget 
      - curl 
      - llvm
language: python
python:
  - "3.4"
install:
  - "pip install hitch"
  - "cd tests"
  - "hitch init"

# whitelist
branches:
  only:
    - master
    - develop

script:
  - "hitch test . --extra '{\"xvfb\":true, \"pause_on_failure\":false}'"

before_install:
  - pip install codecov
after_success:
  - codecov
